apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: lukezzz/ticketing_auth
          context: auth
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
        - image: lukezzz/ticketing_client
          context: client
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "**/*.js"
                    dest: .
        - image: lukezzz/ticketing_tickets
          context: tickets
          docker:
              dockerfile: Dockerfile
          sync:
              manual:
                  - src: "src/**/*.ts"
                    dest: .
