name: tests-orders

on:
    pull_request:
        path:
            - "orders/**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd orders && yarn && yarn test:ci
